<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ClientSeeder extends Seeder
{
    public function run()
    {
        DB::table('client')->insert([
            'NOMBRE' => 'Empresa XYZ',
            'CALLE' => 'Avenida Siempre Viva',
            'NUMERO' => '742',
            'COLONIA' => 'Centro',
            'POBLA' => 'Springfield',
            'CIUDAD' => 'Springfield',
            'ESTADO' => 'Estado',
            'PAIS' => 'USA',
            'TELEFONO' => '555-1234',
            'DIAS' => 30,
            'CREDITO' => 5000.00,
            'DESC1' => 5.00,
            'DESC2' => 10.00,
            'DESC3' => 15.00,
            'DESC4' => 20.00,
            'DESC5' => 25.00,
            'RFC' => 'XYZ123456789',
            'TIPO' => 'Cliente',
            'CONTACTO' => 'John Doe',
            'COBRADOR' => 'Jane Doe',
            'VEND' => 'Juan Perez',
            'PRECIO' => 100.00,
            'CP' => '01100',
            'PROSPECT' => 0,
            'REVISION' => 'Mensual',
            'OBSERV' => 'Cliente importante',
            'ZONA' => 'Norte',
            'CORREO' => 'contacto@empresaxyz.com',
            'URL' => 'www.empresaxyz.com',
            'SALDO' => 0.00,
            'USUARIO' => 'admin',
            'USUHORA' => now(),
            'USUFECHA' => now(),
            'PROVEEDOR' => 'Proveedor Principal',
            'CURB' => 'N/A',
            'CORTE' => 30,
            'COBRO' => 'Cheque',
            'CONCEPTO' => 'Venta',
            'INGRESO' => 'Directo',
            'bloqueado' => 0,
            'claveweb' => 'clave123',
            'emailcobranza' => 'cobranza@empresaxyz.com',
            'embarcar' => 'Sí',
            'comision' => 5.00,
            'foto' => 'default.jpg',
            'puntos' => 100,
            'recomendado' => 'Cliente Recomendado',
            'nuevo' => 'No',
            'F_nac' => '1980-01-01',
            'sexo' => 'Masculino',
            'email' => 'info@empresaxyz.com',
            'TipoA' => 'Tipo A',
            'numerointerior' => '1',
            'numeroexterior' => '2',
            'localidad' => 'Localidad X',
            'saldoSBO' => 0.00,
            'tcf' => 'TCF Example',
            'Exportado' => 1,
            'Vigencia' => now(),
            'TipoWeb' => 'Tipo Web',
            'Activo' => 'Activo',
            'PagoForma' => 'Transferencia',
            'PagoFormaDesc' => 'Transferencia Bancaria',
            'PagoCuenta' => '1234567890',
            'PrePago' => 0,
            'PrePagoDias' => 0,
            'password' => bcrypt('password'),
            'UsoCFDI' => 'G01',
            'PagoMetodo' => 'PUE',
            'moneda' => 'MXN',
            'ValMoneda' => 1,
            'ValCredito' => 1,
            'pagoBanco' => 'Banco XYZ',
            'ApSrv1' => 'Servicio 1',
            'ApSrv2' => 'Servicio 2',
            'CodAct' => 'Codigo Actividad',
            'CodActReg' => 'Codigo Registro',
            'TLIRegApl' => 1,
            'TLIRegArt' => 1,
            'TLIVisitaSuc' => 1,
            'TLIVisitaFch' => 1,
            'Ocupado' => 0,
            'OcupadoSuc' => 0,
            'Regimen' => 'Regimen Fiscal',
            'sucursal' => 'Sucursal Principal'
        ]);
    }
}
