<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\VentaWeb;
use Carbon\Carbon;

class VentaWebSeeder extends Seeder
{
    public function run()
    {
        VentaWeb::create([
            'VENTA' => 1,
            'OCUPADO' => 'SI',
            'TIPO_DOC' => 'FAC',
            'serieDocumento' => 'A001',
            'NO_REFEREN' => '0001',
            'F_EMISION' => Carbon::now(),
            'F_VENC' => Carbon::now()->addDays(30),
            'CLIENTE' => 1,
            'VEND' => 'V001',
            'IMPORTE' => 1000,
            'DESCUENTO' => 50,
            'IMPUESTO' => 160,
            'PRECIO' => 1110,
            'COSTO' => 800,
            'ALMACEN' => 'Central',
            'ESTADO' => 'CO',
            'MONEDA' => 'MXN',
            'USUARIO' => 'admin',
            'USUFECHA' => Carbon::now(),
            'USUHORA' => Carbon::now()->format('H:i:s'),
            'UUID' => 'abcdef123456',
            'OCUPADO' => 0,
            'DESC1' => 5,
            'DESC2' => 10,
            'DESC3' => 15,
            'DESC4' => 20,
            'DESC5' => 25,
            'DATOS' => 'Datos adicionales',
            'ENFAC' => 1,
            'VENTAREF' => 'Ref001',
            'CIERRE' => 1,
            'cierretienda' => 'Tienda001',
            'DESGLOSE' => 'Detallado',
            'COBRANZA' => 'Pendiente',
            'AUTO' => 'Auto001',
            'Relacion' => 'Relacionada001',
            'PEDCLI' => 'PedidoCl001',
            'PEMB' => 'Pendiente',
            'DATEMB' => Carbon::now(),
            'AplicarDes' => 0,
            'TipoVenta' => 'Tipo1',
            'Exportado' => 0,
            'SUCURSAL' => 'Sucursal001',
            'VentaSuc' => 'VentaSuc001',
            'Pago1' => 500,
            'Pago2' => 500,
            'Concepto1' => 'Concepto001',
            'Concepto2' => 'Concepto002',
            'Pago3' => 0,
            'Concepto3' => 'Concepto003',
            'Comision' => 5,
            'VentaOrigen' => 'Origen001',
            'Diario' => 'Diario001',
            'Caja' => 'Caja001',
            'OrigenDev' => 'Devolucion001',
            'Corte' => 'Corte001',
            'Impreso' => 1,
            'BANCO' => 'Banco001',
            'NumeroCheque' => 'Cheque001',
            'estacion' => 'Estacion001',
            'interes' => 2,
            'redondeo' => 0,
            'Ticket' => 'Ticket001',
            'importar' => 0,
            'sucremota' => 'Remota001',
            'ventaremota' => 'VR001',
            'comodin' => 'Comodin001',
            'iespecial' => 'Especial001',
            'nodesglosedetalle' => 0,
            'Transporte' => 'Transporte001',
            'Repartidor' => 'Repartidor001',
            'horasalida' => Carbon::now(),
            'horaregreso' => Carbon::now()->addHours(1),
            'comisiontel' => 3,
            'verificado' => 1,
            'donativo' => 10,
            'pagado' => 1,
            'comisionvendedor' => 5,
            'comodin1' => 'Comodin1001',
            'comodin2' => 'Comodin2001',
            'comodin3' => 'Comodin3001',
            'comodin4' => 'Comodin4001',
            'pago4' => 100,
            'concepto4' => 'Concepto4001',
            'pregunta1' => 'Respuesta1',
            'pregunta2' => 'Respuesta2',
            'pregunta3' => 'Respuesta3',
            'pregunta4' => 'Respuesta4',
            'pregunta5' => 'Respuesta5',
            'fechacierre' => Carbon::now(),
            'businessintelligence' => 'BI001',
            'pedido' => 'Pedido001',
            'cambioDeEstado' => 'Estado001',
            'placas' => 'Placas001',
            'kilometraje' => 1000,
            'color' => 'Azul',
            'serie' => 'Serie001',
            'motor' => 'Motor001',
            'tipo' => 'Tipo001',
            'marca' => 'Marca001',
            'modelo' => 'Modelo001',
            'horaentrega' => Carbon::now(),
            'propina' => 50,
            'paraconcentrador' => 0,
            'felectronica' => Carbon::now(),
            'coriginal' => 'Original001',
            'sdigital' => 'Digital001',
            'ncortez' => 'CorteZ001',
            'archivofe' => 'ArchivoFE001',
            'facturado' => 1,
            'SSMA_TimeStamp' => Carbon::now(),
            'ticketsno' => 'TicketsNO001',
            'ventatipo' => 'VTipo001',
            'motdev' => 'MotivoDev001',
            'facorg' => 'FacOrg001',
            'tipodocorg' => 'TD001',
            'foliodocorg' => 'FolioDocOrg001',
            'pedidoSBO' => 'PedidoSBO001',
            'dAuto' => 'DAuto001',
            'HoraEnt' => Carbon::now(),
            'HoraRecep' => Carbon::now(),
            'retraso' => 0,
            'aefolio' => 'AeFolio001',
            'reproceso' => 1,
            'ususrv' => 'UsuarioSRV001',
            'proxser' => 'ProxSer001',
            'UUID' => 'Unico001',
            'ComprobanteXML' => 'CompXML001',
            'PagoForma' => 'FormaPago001',
            'PagoFormaDesc' => 'DescPago001',
            'PagoCuenta' => 'CuentaPago001',
            'ActWeb' => 1,
            'OcupadoSuc' => 1,
            'Sinc20' => 0,
            'SucSinc' => 'SucSinc001',
            'LogCFDI' => 'LogCFDI001'
        ]);
    }
}
