<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class VentasWebSeeder2 extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('ventas_web')->insert([
            [
                'OCUPADO' => 'No',
                'TIPO_DOC' => 'Factura',
                'serieDocumento' => 'F001',
                'NO_REFEREN' => 'REF123',
                'F_EMISION' => Carbon::now(),
                'F_VENC' => Carbon::now()->addDays(30),
                'CLIENTE' => 1,
                'VEND' => 'Vendedor1',
                'IMPORTE' => 1000.00,
                'DESCUENTO' => 50.00,
                'IMPUESTO' => 180.00,
                'PRECIO' => 1130.00,
                'COSTO' => 800.00,
                'ALMACEN' => 'Principal',
                'ESTADO' => 'Pendiente',
                'OBSERV' => 'Primera venta',
                'TIPO_CAM' => 1.0,
                'MONEDA' => 'USD',
                'DESC1' => 5.00,
                'DESC2' => 0.00,
                'DESC3' => 0.00,
                'DESC4' => 0.00,
                'DESC5' => 0.00,
                'DATOS' => 'Datos adicionales',
                'ENFAC' => 0,
                'VENTAREF' => 0,
                'CIERRE' => 0,
                'cierretienda' => 0,
                'DESGLOSE' => 'Desglose de productos',
                'COBRANZA' => 0,
                'USUARIO' => 'Admin',
                'USUFECHA' => Carbon::now(),
                'USUHORA' => Carbon::now()->toTimeString(),
                'AUTO' => 0,
                'Relacion' => 'Relacionada',
                'PEDCLI' => 'PED123',
                'PEMB' => 0,
                'DATEMB' => Carbon::now(),
                'AplicarDes' => 0,
                'TipoVenta' => 'Online',
                'Exportado' => 0,
                'SUCURSAL' => 'Sucursal1',
                'VentaSuc' => 'Venta1',
                'Pago1' => 500.00,
                'Pago2' => 200.00,
                'Concepto1' => 'Pago efectivo',
                'Concepto2' => 'Pago tarjeta',
                'Pago3' => 430.00,
                'Concepto3' => 'Pago transferencia',
                'Comision' => 10.00,
                'VentaOrigen' => 'Online',
                'Diario' => 'Diario1',
                'Caja' => 'Caja1',
                'OrigenDev' => 'No',
                'Corte' => 'Corte1',
                'Impreso' => 0,
                'BANCO' => 'Banco1',
                'NumeroCheque' => 'CHEQ123',
                'estacion' => 'Estacion1',
                'interes' => 2.50,
                'redondeo' => 0.00,
                'Ticket' => 'TICKET123',
                'importar' => 0,
                'sucremota' => 'SucursalRemota1',
                'ventaremota' => 'VentaRemota1',
                'comodin' => 'Comodin1',
                'iespecial' => 0,
                'nodesglosedetalle' => 0,
                'Transporte' => 'Transporte1',
                'Repartidor' => 'Repartidor1',
                'horasalida' => Carbon::now()->toTimeString(),
                'horaregreso' => Carbon::now()->addHours(2)->toTimeString(),
                'comisiontel' => 5.00,
                'verificado' => 0,
                'donativo' => 0,
                'pagado' => 0,
                'comisionvendedor' => 15.00,
                'comodin1' => 'ComodinA',
                'comodin2' => 'ComodinB',
                'comodin3' => 'ComodinC',
                'comodin4' => 'ComodinD',
                'pago4' => 100.00,
                'concepto4' => 'Pago en efectivo',
                'pregunta1' => 'Pregunta 1',
                'pregunta2' => 'Pregunta 2',
                'pregunta3' => 'Pregunta 3',
                'pregunta4' => 'Pregunta 4',
                'pregunta5' => 'Pregunta 5',
                'fechacierre' => Carbon::now()->addDays(30),
                'businessintelligence' => 'Datos BI',
                'pedido' => 'PED789',
                'cambioDeEstado' => 'En proceso',
                'placas' => 'ABC123',
                'kilometraje' => '12000',
                'color' => 'Rojo',
                'serie' => 'SERIE123',
                'motor' => 'MOTOR123',
                'tipo' => 'SUV',
                'marca' => 'Marca1',
                'modelo' => 'Modelo1',
                'horaentrega' => Carbon::now()->addHours(4)->toTimeString(),
                'propina' => 20.00,
                'paraconcentrador' => 0,
                'felectronica' => 'FE123',
                'coriginal' => 0,
                'sdigital' => 0,
                'ncortez' => 'NCORTEZ123',
                'archivofe' => 'Archivo FE',
                'facturado' => 0,
                'SSMA_TimeStamp' => Carbon::now(),
                'ticketsno' => 'TICKET456',
                'ventatipo' => 'TipoVenta1',
                'motdev' => 'Motivo devolución',
                'facorg' => 'FAC123',
                'tipodocorg' => 'TipoDocOrg1',
                'foliodocorg' => 'FolioDocOrg1',
                'pedidoSBO' => 'Pedido SBO',
                'dAuto' => 0,
                'HoraEnt' => Carbon::now()->addHours(5)->toTimeString(),
                'HoraRecep' => Carbon::now()->toTimeString(),
                'retraso' => 0,
                'aefolio' => 'AEF123',
                'reproceso' => 0,
                'ususrv' => 'UsuarioSRV',
                'proxser' => Carbon::now()->addMonths(6),
                'UUID' => 'UUID123',
                'ComprobanteXML' => 'Comprobante XML',
                'PagoForma' => 'FormaPago1',
                'PagoFormaDesc' => 'Descripción Forma Pago',
                'PagoCuenta' => 'CuentaPago1',
                'ActWeb' => 0,
                'OcupadoSuc' => 0,
                'Sinc20' => 0,
                'SucSinc' => 'SucSinc1',
                'LogCFDI' => 'Log CFDI',
            ],
            // Puedes agregar más registros aquí...
        ]);
    }
}
