<?php

namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VentasWebTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('ventas_web')->insert([
            [
                'VENTA' => 1,
                'OCUPADO' => 'SI',
                'TIPO_DOC' => 'FACT',
                'serieDocumento' => 'F001-',
                'NO_REFEREN' => 'REF123',
                'F_EMISION' => '2024-05-01',
                'F_VENC' => '2024-06-01',
                'CLIENTE' => 'Cliente 1',
                'VEND' => 'Vendedor A',
                'IMPORTE' => 1500.00,
                'DESCUENTO' => 50.00,
                'IMPUESTO' => 150.00,
                'PRECIO' => 1600.00,
                'COSTO' => 800.00,
                'ALMACEN' => 'Central',
                'ESTADO' => 'CO',
                'OBSERV' => 'Ninguna observación',
                'TIPO_CAM' => '1.00',
                'MONEDA' => 'MXN',
                'DESC1' => 1,
                'DESC2' => null,
                'DESC3' => null,
                'DESC4' => null,
                'DESC5' => null,
                'DATOS' => 'Detalles adicionales aquí',
                'ENFAC' => 1,
                'VENTAREF' => 1,
                'CIERRE' => 1,
                'cierretienda' => 1,
                'DESGLOSE' => 'SI',
                'COBRANZA' => 1,
                'USUARIO' => 'admin',
                'USUFECHA' => '2024-05-01',
                'USUHORA' => '08:00:00',
                'AUTO' => 1,
                'Relacion' => null,
                'PEDCLI' => null,
                'PEMB' => 1,
                'DATEMB' => null,
                'AplicarDes' => 1,
                'TipoVenta' => 'Normal',
                'Exportado' => 1,
                'SUCURSAL' => 'Sucursal 1',
                'VentaSuc' => 'Sucursal 1',
                'Pago1' => 500.00,
                'Pago2' => 1000.00,
                'Concepto1' => 'Anticipo',
                'Concepto2' => 'Pago final',
                'Pago3' => null,
                'Concepto3' => null,
                'Comision' => 100.00,
                'VentaOrigen' => 'Online',
                'Diario' => 'D001',
                'Caja' => 'C001',
                'OrigenDev' => null,
                'Corte' => null,
                'Impreso' => 1,
                'BANCO' => 'Banamex',
                'NumeroCheque' => '123456',
                'estacion' => 'Estacion 1',
                'interes' => 0.00,
                'redondeo' => 0.00,
                'Ticket' => 'TCKT001',
                'importar' => 1,
                'sucremota' => 1,
                'ventaremota' => 1,
                'comodin' => 1,
                'iespecial' => 1,
                'nodesglosedetalle' => 1,
                'Transporte' => 'DHL',
                'Repartidor' => 'Juan Perez',
                'horasalida' => '09:00:00',
                'horaregreso' => '11:00:00',
                'comisiontel' => 0.00,
                'verificado' => 1,
                'donativo' => 0.00,
                'pagado' => 1,
                'comisionvendedor' => 50.00,
                'comodin1' => null,
                'comodin2' => null,
                'comodin3' => null,
                'comodin4' => null,
                'pago4' => null,
                'concepto4' => null,
                'pregunta1' => null,
                'pregunta2' => null,
                'pregunta3' => null,
                'pregunta4' => null,
                'pregunta5' => null,
                'fechacierre' => null,
                'businessintelligence' => null,
                'pedido' => null,
                'cambioDeEstado' => null,
                'placas' => '123ABC',
                'kilometraje' => '50000',
                'color' => 'Rojo',
                'serie' => 'Serie123',
                'motor' => 'Motor123',
                'tipo' => 'Sedán',
                'marca' => 'Toyota',
                'modelo' => 'Corolla',
                'horaentrega' => '12:00:00',
                'propina' => 0.00,
                'paraconcentrador' => 1,
                'felectronica' => '2024-05-01',
                'coriginal' => 1,
                'sdigital' => 1,
                'ncortez' => 'Corte123',
                'archivofe' => 'ArchivoFE123',
                'facturado' => 1,
                'SSMA_TimeStamp' => null,
                'ticketsno' => 'TCKTS001',
                'ventatipo' => 'Tipo1',
                'motdev' => 'Motivo123',
                'facorg' => 'Factura123',
                'tipodocorg' => 'Doc123',
                'foliodocorg' => 'Folio123',
                'pedidoSBO' => 'PedidoSBO123',
                'dAuto' => 1,
                'HoraEnt' => '13:00:00',
                'HoraRecep' => '14:00:00',
                'retraso' => 0.00,
                'aefolio' => 'AEFolio123',
                'reproceso' => 1,
                'ususrv' => 'UserServ123',
                'proxser' => '2024-05-20',
                'UUID' => 'UUID123',
                'ComprobanteXML' => 'ComprobanteXML123',
                'PagoForma' => 'Efectivo',
                'PagoFormaDesc' => 'Pago en efectivo',
                'PagoCuenta' => 'Cuenta123',
                'ActWeb' => 1,
                'OcupadoSuc' => 1,
                'Sinc20' => 1,
                'SucSinc' => 1,
                'LogCFDI' => 'LogCFDI123'
            ]
        ]);
    }
}
